In [1]:
!pip install numpy

In [1]:
import numpy as np
a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [16]:
b = np.array([[1,3,5],[2,4,6]])
print(b)

[[1 3 5]
 [2 4 6]]


In [5]:
a.dtype

dtype('int64')

In [6]:
a.ndim

1

In [7]:
b.ndim

2

In [8]:
a.shape

(6,)

In [9]:
b.shape

(2, 3)

In [10]:
a.itemsize

8

In [11]:
a.nbytes

48

In [12]:
x = np.array([0,1,2,3,4,5,6,7,8,9])
x[1:7:2]

array([1, 3, 5])

In [14]:
b[0][1]

np.int64(3)

In [17]:
b[1][2]

np.int64(6)

In [18]:
print(b)

[[1 3 5]
 [2 4 6]]


In [19]:
b.reshape(3,2)

array([[1, 3],
       [5, 2],
       [4, 6]])

In [20]:
print(b)

[[1 3 5]
 [2 4 6]]


In [21]:
b.swapaxes(0,1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [22]:
c = b.flatten()
c

array([1, 3, 5, 2, 4, 6])

In [23]:
np.sort(c)

array([1, 2, 3, 4, 5, 6])

### Space Saving

In [25]:
data = np.arange(0,1000)
print(data.dtype)

int64


In [26]:
print(data.nbytes)

8000


In [27]:
data = np.arange(0,1000, dtype = 'int8')
print(data.dtype)

int8


In [28]:
print(data.nbytes)

1000


In [4]:
d = np.arange(1,10,2)
d

array([1, 3, 5, 7, 9])

In [5]:
e = np.linspace(1,10,5)
e

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [6]:
f = np.zeros((2,2))
f

array([[0., 0.],
       [0., 0.]])

In [7]:
g = np.ones((3,3))
g

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
h = np.full((5,),7)
h

array([7, 7, 7, 7, 7])

In [10]:
i = np.full((5,2),9)
i

array([[9, 9],
       [9, 9],
       [9, 9],
       [9, 9],
       [9, 9]])

In [12]:
j = np.fromstring('5 10 15 20 25', dtype=int, sep=' ')
j

array([ 5, 10, 15, 20, 25])

In [13]:
j.dtype

dtype('int64')

In [14]:
np.around([0.37, 1.64, 1.5, 1.49])

array([0., 2., 2., 1.])

In [16]:
np.around([0.37, 1.64, 1.5, 1.49], decimals=1)

array([0.4, 1.6, 1.5, 1.5])

In [17]:
a.sum()

np.int64(21)

In [18]:
a = np.array([[1,2,3],[4,5,6]])
a.sum()

np.int64(21)

In [19]:
a.sum(axis=0)

array([5, 7, 9])

In [20]:
a.sum(axis=1)

array([ 6, 15])

In [22]:
price = np.array([350, 500,400, 250,150])
print('min price:', price.min())
print('max price:', price.max())
print('mean price:', price.mean())
print('variance price:', price.var())
print('standard deviation price:', price.std())

min price: 150
max price: 500
mean price: 330.0
variance price: 14600.0
standard deviation price: 120.83045973594572


In [23]:
print(price)

[350 500 400 250 150]


In [24]:
price.argmin()

np.int64(4)

In [25]:
price.argmax()

np.int64(1)

In [27]:
textData = np.loadtxt('data.txt', skiprows=1, delimiter=',', dtype=np.int32)
textData

array([[ 1,  2,  3,  4,  5],
       [ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10],
       [ 2,  3,  5,  7, 11],
       [ 2,  4,  8, 16, 32]], dtype=int32)

In [28]:
textData = np.genfromtxt('data.txt', skip_header=1, delimiter=',', dtype=np.int32)
textData

array([[ 1,  2,  3,  4,  5],
       [ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10],
       [ 2,  3,  5,  7, 11],
       [ 2,  4,  8, 16, 32]], dtype=int32)

In [29]:
multipleFive = textData*5
multipleFive

array([[  5,  10,  15,  20,  25],
       [  5,  15,  25,  35,  45],
       [ 10,  20,  30,  40,  50],
       [ 10,  15,  25,  35,  55],
       [ 10,  20,  40,  80, 160]], dtype=int32)

In [30]:
np.savetxt('newData.txt', multipleFive, delimiter=',', fmt='%d', header='v1,v2,v3,v4,v5', comments='')