In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [16]:
df = pd.read_csv('regression-one.csv')
df.head()

Country  Year      Status  Life expectancy  Adult Mortality  \
0  Afghanistan  2015  Developing             65.0            263.0   
1  Afghanistan  2014  Developing             59.9            271.0   
2  Afghanistan  2013  Developing             59.9            268.0   
3  Afghanistan  2012  Developing             59.5            272.0   
4  Afghanistan  2011  Developing             59.2            275.0   

   infant deaths  Alcohol  percentage expenditure  Hepatitis B  Measles  ...  \
0             62     0.01               71.279624         65.0     1154  ...   
1             64     0.01               73.523582         62.0      492  ...   
2             66     0.01               73.219243         64.0      430  ...   
3             69     0.01               78.184215         67.0     2787  ...   
4             71     0.01                7.097109         68.0     3013  ...   

   Polio  Total expenditure  Diphtheria  HIV/AIDS         GDP  Population  \
0    6.0               8.16        65.0       0.1  584.259210  33736494.0   
1   58.0               8.18        62.0       0.1  612.696514    327582.0   
2   62.0               8.13        64.0       0.1  631.744976  31731688.0   
3   67.0               8.52        67.0       0.1  669.959000   3696958.0   
4   68.0               7.87        68.0       0.1   63.537231   2978599.0   

   thinness 1-19 years  thinness 5-9 years  Income composition of resources  \
0                 17.2                17.3                            0.479   
1                 17.5                17.5                            0.476   
2                 17.7                17.7                            0.470   
3                 17.9                18.0                            0.463   
4                 18.2                18.2                            0.454   

   Schooling  
0       10.1  
1       10.0  
2        9.9  
3        9.8  
4        9.5  

[5 rows x 22 columns]

In [31]:
df.rename(columns = {'Life expectancy': 'life-expect'}, inplace=True)
df = df.dropna()
df.shape

(1649, 22)

In [32]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [Country, Year, Status, life-expect, Adult Mortality, infant deaths, Alcohol, percentage expenditure, Hepatitis B, Measles, BMI, under-five deaths, Polio, Total expenditure, Diphtheria, HIV/AIDS, GDP, Population, thinness 1-19 years, thinness 5-9 years, Income composition of resources, Schooling]
Index: []

[0 rows x 22 columns]

In [33]:
from sklearn.linear_model import LinearRegression
slr = LinearRegression()
slrX = df[['Schooling']]
Y = df['life-expect']
slr.fit(slrX, Y)

LinearRegression()

In [34]:
slrYhat = slr.predict(slrX)

In [35]:
print(slrYhat[0:4])

[64.6771856  64.44820695 64.2192283  63.99024965]


In [22]:
from sklearn.metrics import mean_squared_error

slr_MSE = mean_squared_error(df['life-expect'], slrYhat)
print('MSE for Simple Linear Regression: ', slr_MSE)

MSE for Simple Linear Regression:  36.39144686879598


In [36]:
slr_RSquared = slr.score(slrX, Y)
print('RSquared for Simple Linear Regression: ', slr_RSquared)

RSquared for Simple Linear Regression:  0.5294454639356108


In [39]:
mlr = LinearRegression()
mlrX = df[['GDP', 'Alcohol', 'BMI', 'Schooling']]
mlr.fit(mlrX, Y)

LinearRegression()

In [41]:
mlrYhat = mlr.predict(mlrX)
print(mlrYhat[0:4])

[64.24861418 64.01295717 63.77621795 63.54168785]


In [42]:
mlr_MSE = mean_squared_error(df['life-expect'], mlrYhat)
print('MSE for Multiple Linear Regression: ', mlr_MSE)

MSE for Multiple Linear Regression:  32.66263978796142


In [43]:
mlr_RSquared = mlr.score(mlrX, Y)
print('RSquared for Multiple Linear Regression: ', mlr_RSquared)

RSquared for Multiple Linear Regression:  0.5776602846411929


In [44]:
prX = df['Schooling']
f = np.polyfit(prX,Y,3)
pr = np.poly1d(f)

In [45]:
prYhat = pr(prX)
print(prYhat[0:4])

[63.54170723 63.28970051 63.04117145 62.79627248]


In [46]:
pr_MSE = mean_squared_error(df['life-expect'], prYhat)
print('MSE for Polynomial Regression: ', pr_MSE)

MSE for Polynomial Regression:  34.73390295312004


In [48]:
from sklearn.metrics import r2_score

pr_RSquared = r2_score(df['life-expect'], prYhat)
print('RSquared for Polynomial Regression: ', pr_RSquared)

RSquared for Polynomial Regression:  0.5508781047168168


#### Simple Linear Regression

In [49]:
print('MSE for Simple Linear Regression: ', slr_MSE)
print('RSquared for Simple Linear Regression: ', slr_RSquared)

MSE for Simple Linear Regression:  36.39144686879598
RSquared for Simple Linear Regression:  0.5294454639356108


#### Multiple Linear Regression

In [50]:
print('MSE for Multiple Linear Regression: ', mlr_MSE)
print('RSquared for Multiple Linear Regression: ', mlr_RSquared)

MSE for Multiple Linear Regression:  32.66263978796142
RSquared for Multiple Linear Regression:  0.5776602846411929


#### Polynomial Regression

In [51]:
print('MSE for Polynomial Regression: ', pr_MSE)
print('RSquared for Polynomial Regression: ', pr_RSquared)

MSE for Polynomial Regression:  34.73390295312004
RSquared for Polynomial Regression:  0.5508781047168168
